#!/usr/bin/env python

# NOTES 
# angr has fundamental limitation with stdin inputs, thus all target binaries must only
# take input from files

import sys
import os
import time
import socket
import signal
import subprocess32
import re

try:
    import shellphish_qemu
except ImportError:
    raise ImportError("Import Error for shellphish_qemu")

import itertools
import angr
from angr.exploration_techniques import CrashMonitor, Oppologist

"""
class SafeOpen(angr.SimProcedure):
  def run(self, path_addr, flags, mode=None):
    try:
      path_str = self.state.mem[path_addr].string.concrete
    except Exception as e:
      print "[!] SafeOpen: Failed to resulve path string from addr %s" % path_addr
      return -1
    print "[+] SafeOpen: Opening file '%s'" % path_str
    return self.state.posix.open(path_str, flags)
"""

# Function for Tracing the target binary
def trace(binary_path, argv, input_data, stdin, tracer, trace_log):
  # Set arguments for tracer
  args = [tracer]
  args += ["-d", "exec", "-D", trace_log]
  args += [binary_path] + list(argv)

  with open('/dev/null', 'wb') as devnull:
    # Clear and save environment variable QEMU_LD_PREFIX
    x = os.environ['QEMU_LD_PREFIX'] if 'QEMU_LD_PREFIX' in os.environ else None
    os.environ['QEMU_LD_PREFIX'] = ''

    # Run the tracer
    # Case when binary takes input from stdin
    if int(stdin) == 1:
      print "[+] Binary takes input through stdin"
      in_s, out_s = socket.socketpair()
      p = subprocess32.Popen(args, stdin=in_s, stdout=devnull, stderr=devnull)
      for write in input_data:
        out_s.send(write)
        time.sleep(.01)
      out_s.close()
    # Case when binary takes input from file
    else:
      print "[+] Binary takes input as file"
      p = subprocess32.Popen(args, stdin=subprocess32.PIPE, stdout=devnull, stderr=devnull)
      _, _ = p.communicate(input_data)

    # Reset environment variable QEMU_LD_PREFIX
    os.environ['QEMU_LD_PREFIX'] = x if x is not None else ''

    # Check for crash
    ret = p.wait()
    crash = False
    print "[+] Return value: %d" % ret
    if abs(ret) == signal.SIGSEGV or abs(ret) == signal.SIGILL:
      crash = True
      print "[!] Input caused crash during tracing"

    # Manage the trace log
    trace_file = open(trace_log).read()
    addrs = []
    qemu_base_addr = int(trace_file.split("start_code")[1].split("\n")[0], 16)
    prog = re.compile(r'Trace (.*) \[(?P<addr>.*)\].*')
    for t in trace_file.split('\n'):
      m = prog.match(t)
      if m != None:
        addr_str = m.group('addr')
        addrs.append(int(addr_str, base=16))
      else:
        continue
    
    # Find crash_addr
    crash_addr = None
    if crash:
      crash_addr = trace_file.split('\n')[-2].split('[')[1].split(']')[0]
      print "[+] Crash Addr: %s" % crash_addr
      crash_addr = int(crash_addr, 16)

    return {'trace': addrs, 'crash': crash, 'crash_addr': crash_addr}


num_constraints = 0

# Function for Collecting Constraints
def collect_constraints(trace, crash, crash_addr, binary_path, input_data, argv):
  # Check Crash
  if not crash:
    print "[!] No crash detected"
  
  # Setup angr
  p = angr.Project(binary_path)#, exclude_sim_procedures_list=('malloc', 'free', 'calloc', 'realloc'))
  p.hook_symbol('set_program_name', angr.SIM_PROCEDURES['stubs']['ReturnUnconstrained']())
  p.hook_symbol('setlocale', angr.SIM_PROCEDURES['stubs']['ReturnUnconstrained']())
  p.hook_symbol('bindtextdomain', angr.SIM_PROCEDURES['stubs']['ReturnUnconstrained']())
  p.hook_symbol('textdomain', angr.SIM_PROCEDURES['stubs']['ReturnUnconstrained']())
  p.hook_symbol('posix_fadvise64', angr.SIM_PROCEDURES['stubs']['ReturnUnconstrained']())
  p.hook_symbol('dcgettext', angr.SIM_PROCEDURES['stubs']['ReturnUnconstrained']())
  p.hook_symbol('atexit', angr.SIM_PROCEDURES['libc']['atexit']())
  #p.hook_symbol('open', SafeOpen())
  p.hook_symbol('fopen_custom', angr.SIM_PROCEDURES['libc']['fopen']())

  prc = angr.SIM_PROCEDURES['stubs']['getopt_long']()
  prc._ret_seq = [ord('d'), -1]
  prc._ret_c = itertools.count()

  # Change to dynamic lookup??
  #prc._optind_addr = 0x080571b4
  optind_symbol = p.loader.main_object.get_symbol('optind')
  if optind_symbol:
    print "[+] Found optind dynamically at:", hex(optind_symbol.rebased_addr)
    prc._optind_addr = optind_symbol.rebased_addr
  else:
    print "[!] Could not find explicit optind symbol"
    prc._optind_addr = 0x080571b4

  p.hook_symbol('getopt_long', prc)

  target_opts = [binary_path] + argv
  
  # NOTE stdin does not work in angr
  content = {'input_file': input_data}
  #content = {'stdin': "\n".join(input_data)}
  state1 = p.factory.tracer_state(input_content=content, preconstrain_input=True, args=target_opts)

  crashing_block = p.factory.block(crash_addr)
  collected_constraints = []
  offending_constraints = []

  def inspect_func(state):
    global num_constraints
    sc = state.added
    if not state.satisfiable() or len(sc) == 0:
      return

    if state.addr in [0x8049554, 0x804955a, 0x9067084]:
      return

    if state.addr in crashing_block.instruction_addrs:
      return

    if state.addr in [0x804b32d]:
      # TODO Add to offending constraints?
      return

    # TODO check if constraint was transformed?
    collected_constraints.extend(sc)
    
    print "[+] Constraint at: ", hex(state.addr)
    print "[+] Constraint expression: \n", sc
    num_constraints += 1

  state1.inspect.b('constraints', when=angr.BP_AFTER, action=inspect_func)
  simgr = p.factory.simgr(state1, save_unsat=False, hierarchy=False, save_unconstrained=False)
  t = angr.exploration_techniques.Tracer(trace=trace)
  
  print("\n==================== PRINTING TRACE ====================\n")
  for addr in trace: 
    block = p.factory.block(addr)
    print("Block @ {}",format(hex(addr)))
    block.pp()  # pretty-print disassembly
  print("\n================== PRINTING CONSTRAINTS ================\n")
  simgr.use_technique(t)
  simgr.use_technique(angr.exploration_techniques.Oppologist())
  simgr.run()
  print "\nTotal Number of Constraints: ", num_constraints


# main
def main():
  # Check args
  if len(sys.argv) < 3:
    print "Usage: %s <binary> <input_file> <tracer> <trace_log>" % sys.argv[0]  
    sys.exit(1)

  binary = sys.argv[1]
  binary_path = os.path.abspath(binary)
  argv = ["-zR3"]
  #argv = ["-d"];
  #argv = [];
  input_file = sys.argv[2]
  input_data = None

  stdin = 0
  
  # There is no stdin support
  """
  if int(stdin) == 1:
    input_data = []
    try:
      with open(input_file, 'r') as f:
        for line in f:
          input_data.append(line.strip())
    except IOError as e:
      print "[!] Error reading input file"
      sys.exit(1)
  else:
    input_data = input_file
    argv += [input_file] 
  """

  input_data = input_file
  argv += [input_file] 
    
  # tracer 
  # x86 arch, 64 bit -> linux-x86_64
  # x86 arch, 32 bit -> linux-i386
  tracer = sys.argv[3]
  trace_path = shellphish_qemu.qemu_path(tracer)
  if not os.access(trace_path, os.X_OK):
    print "[!] Tracer invalid"
    sys.exit(1)
  trace_log = sys.argv[4]

  # Trace the binary
  print "[+] Tracing binary with input"
  print input_data
  trace_results = trace(binary_path, argv, input_data, stdin, trace_path, trace_log)
  print "[+] Tracing Complete"

  # Collect Constraints
  print "[+] Collect Constraints from binary"
  collect_constraints(trace_results['trace'], trace_results['crash'], trace_results['crash_addr'], binary_path, input_data, argv)
  print "[+] Collect Constrints Complete"
  return


if __name__ == '__main__':
  main()
